---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple                   
        livenessProbe:
          httpGet:
            path: /health
            port: 8081

