apiVersion: v1
data:
  application.properties: |
    QA=TRUE
kind: ConfigMap
metadata:
  name: qa-example-configmap
  namespace: qa
---
apiVersion: v1
kind: Service
metadata:
  name: qa-simple-service
  namespace: qa
spec:
  ports:
  - name: qa-port
    nodePort: 31000
    port: 8080
    protocol: TCP
  - name: internal-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: trivial-go-web-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    codefresh.io/app: simple-go-app
  name: qa-simple-deployment
  namespace: qa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - env:
        - name: UI_THEME
          value: light
        - name: CACHE_SIZE
          value: 2048kb
        - name: PAGE_LIMIT
          value: "25"
        - name: SORTING
          value: ascending
        - name: N_BUCKETS
          value: "42"
        - name: ENV
          value: qa
        - name: GPU_ENABLED
          value: "0"
        - name: ENV_TYPE
          value: non-prod
        - name: PAYPAL_URL
          value: staging2.paypal.com
        - name: DB_USER
          value: non-prod-user
        - name: DB_PASSWORD
          value: non-prod-password
        - name: REGION
          value: us
        image: docker.io/kostiscodefresh/simple-env-app:3.0
        imagePullPolicy: Always
        name: webserver-simple
        ports:
        - containerPort: 8080
